accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup')
]

reviews/urls.py
from django.urls import path, include
from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.ReviewList.as_view(template_name='review_list.html'), name="all"),
    path('new/', views.CreateReview.as_view(template_name='review_form.html'), name="create"),
]

wegrow/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('about/', views.AboutPage.as_view(), name='about'),
    path('profile/', views.ProfilePage.as_view(), name='profile')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User, PermissionsMixin

class User(User, PermissionsMixin):

    def __str__(self):
        return self.username

reviews/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse

User = get_user_model()

class Review(models.Model):
    user = models.ForeignKey(User, related_name='reviews', on_delete='CASCADE')
    title = models.CharField(max_length=200, unique=False)
    rating = models.IntegerField(default=3, validators=[MaxValueValidator(5), MinValueValidator(0)])
    body = models.TextField()
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('reviews:all')

    class Meta:
        ordering = ['-created_at']

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Username'
        self.fields['password2'].label = 'Retype Password'
        self.fields['password2'].help_text = ''
        self.fields['email'].label = 'Email'

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy
from . import forms

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

reviews/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from . import models
from . import forms

class ReviewList(generic.ListView):
    model = models.Review

class CreateReview(LoginRequiredMixin, generic.CreateView):
    model = models.Review
    fields = ('title', 'body', 'rating')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

wegrow/views.py
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'index.html'

class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

class AboutPage(TemplateView):
    template_name = 'about.html'

class ProfilePage(TemplateView):
    template_name = 'profile.html'

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container content">
  <h2>Log In</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="Login">
  </form>
  <br>
  <p>Don't have an account?</p>
  <a href="{% url 'accounts:signup' %}">Sign Up</a>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="container content">
  <h2>Sign Up</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="Sign Up">
  </form>
  <p>Already have an account?</p>
  <a href="{% url 'accounts:login' %}">Log In</a>
</div>
{% endblock %}

reviews/templates/_review.html
<div class="card review-card">
  <div class="card-body review-card-body">
    <h3 class="card-title reviews-title">{{review.title}}</h3>
    <h3>Rating: {{review.rating}}/5</h3>
    <h5>by: {{review.user.username}}</h5>
    <h5>Created at {{review.created_at}}</h5>
    <p class="card-text card-center">{{review.body}}</p>
  </div>
</div>

reviews/templates/review_form.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h4>Write a New Review</h4>
  <form id="reviewForm" action="{% url 'reviews:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary btn-large" value="POST">
  </form>
</div>
{% endblock %}

reviews/templates/review_list.html
{% extends "base.html" %}

{% block content %}
  <div class="card">
    <div class="card-body review-card-body">
      <h1 class="card-title reviews-title">Reviews</h1>
    </div>
  </div>
  <a class="btn btn-success" href="{% url 'reviews:create' %}">Write a Review</a>
  <div class="reviews-list">
    {% if review_list %}
      {% for review in review_list %}
        {% include "_review.html" %}
      {% endfor %}
    {% else %}
      <h2>No reviews to show.</h2>
    {% endif %}
  </div>

{% endblock content %}

templates/about.html
{% extends "base.html" %}

{% block content %}
<div class="card intro-card-div2">
  <div class="card-body intro-card-body">
    <h1 class="card-title reviews-title">About CLC</h1>
    <p class="card-text card-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
</div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>CLC</title>
    <link rel="icon" type="image/png" href="{% static 'clcicon.png' %}"/>
    <link rel="stylesheet" href="{% static 'master.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  </head>
  <body>
    <nav class='navbar navbar-expand mynav' role='navigation' id='navbar'>
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Currier Lawn Care</a>
        <ul class='nav mr-auto'>
          {% if user.is_authenticated %}
            <li class='nav-item'>
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            <li class='nav-item'>
              <a class="nav-link" href="#">Schedule Service</a>
            </li>
            <li class='nav-item'>
              <a class="nav-link" href="{% url 'reviews:all' %}">Reviews</a>
            </li>
            <li class='nav-item'>
              <a class="nav-link" href="{% url 'profile' %}">Your Profile</a>
            </li>
            <li class='nav-item'>
              <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            </li>
          {% else %}
            <li class='nav-item'>
              <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            </li>
            <li class='nav-item'>
              <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    {% block content %}

    {% endblock %}
  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
  {% if user.is_authenticated %}
    <div class="card intro-card-div">
      <div class="card-body intro-card-body">
        <h3 class="card-title">Welcome, {{user.username}}</h3>
        <p class="card-text card-center">How can we help you today?</p>
      </div>
    </div>
  {% else %}
    <div class="card intro-card-div2">
      <div class="card-body intro-card-body">
        <h3 class="card-title card-center">Welcome to <br>Currier Lawn Care</h3>
        <p class="card-text card-center">Please login or sign up for a free account to schedule service and see customer reviews.</p>
      </div>
    </div>
  {% endif %}

{% endblock content %}

templates/profile.html
{% extends "base.html" %}

{% block content %}
<div class="card intro-card-div2">
  <div class="card-body intro-card-body">
    <h1 class="card-title reviews-title">Your Profile</h1>
    <p class="card-text card-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
</div>
{% endblock content %}